language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - valgrind
      - csh
      - g++-multilib
      - gcc-multilib

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # Create a test environment
  - conda create --yes -n test python=$python
  # Activate the test environment
  - source activate test
  - conda install --yes --quiet pip
  # Build the recipe
  - conda build devtools/conda-recipe
  # Install the package
  - conda install --yes --use-local ${PACKAGENAME}
  # Install testing dependencies
  - conda install --yes --quiet nose nose-timer
  # Test the package
  - cd tests && nosetests . --nocapture --verbosity=2 --with-timer -a '!slow' && cd ..

env:
  matrix:
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36

  global:
    - ORGNAME="omnia"
    - PACKAGENAME="yank-examples"
