language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - valgrind
      - csh
      - g++-multilib
      - gcc-multilib

branches:
  only:
    - master

before_install:
  # Configure environment.
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  # Unpack encrypted OpenEye license file
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ] ; then openssl aes-256-cbc -K $encrypted_26d6bc703718_key -iv $encrypted_26d6bc703718_iv -in devtools/travis-ci/oe_license.txt.enc -out $HOME/oe_license.txt -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ] ; then echo "OpenEye license will not be installed in pull request."; fi

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # Create a test environment
  - conda create --yes -n test python=$python
  # Activate the test environment
  - source activate test
  - conda install --yes --quiet pip
  # Build the recipe
  - conda build devtools/conda-recipe
  # Install the package
  - conda install --yes --use-local ${PACKAGENAME}
  # Install testing dependencies
  - conda install --yes --quiet nose nose-timer pytest
  # Install OpenEye dependencies
  - pip install -i https://pypi.anaconda.org/OpenEye/simple OpenEye-toolkits && python -c "import openeye; print(openeye.__version__)"
  # Test the package
  - cd tests && pytest test_syntax.py; cd ..
  - cd tests && nosetests . --nocapture --verbosity=2 --with-timer -a '!slow' && cd ..

env:
  matrix:
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36

  global:
    - ORGNAME="omnia"
    - PACKAGENAME="yank-examples"
