package:
  name: yank-examples
  version: !!str 0.0.0

source:
  path: ../..

requirements:
  build:
    - yank >=0.17.0

  run:
    - yank >=0.17.0


about:
  home: https://github.com/choderalab/yank-examples
  license: MIT License
